# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_directory', models.CharField(max_length=50)),
                ('goals', models.CharField(max_length=20)),
                ('ftp_hostname', models.CharField(max_length=20)),
                ('ftp_port', models.CharField(max_length=20)),
                ('ftp_username', models.CharField(max_length=20)),
                ('ftp_password', models.CharField(max_length=20)),
                ('ftp_tomcat_stop', models.CharField(max_length=50)),
                ('ftp_tomcat_start', models.CharField(max_length=50)),
                ('ftp_ps', models.CharField(max_length=50)),
                ('ftp_war_path', models.CharField(max_length=50)),
                ('ftp_war_back_path', models.CharField(max_length=50)),
            ],
        ),
    ]
