# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_environmentvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentvariable',
            name='ftp_war_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
