# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0005_auto_20170712_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentvariable',
            name='profile',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
